// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpi15viRhXCIbYCSgyEx17kX6qRsa4dDU',
    appId: '1:308335910092:web:c8841d589da8c0e20cf669',
    messagingSenderId: '308335910092',
    projectId: 'ebox-42cef',
    authDomain: 'ebox-42cef.firebaseapp.com',
    databaseURL: 'https://ebox-42cef-default-rtdb.firebaseio.com',
    storageBucket: 'ebox-42cef.appspot.com',
    measurementId: 'G-Z9VGZVJ56B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8mYhyx717YVuKl9-cxVU16qobgvkK7u8',
    appId: '1:308335910092:android:0ec8f345ff9865710cf669',
    messagingSenderId: '308335910092',
    projectId: 'ebox-42cef',
    databaseURL: 'https://ebox-42cef-default-rtdb.firebaseio.com',
    storageBucket: 'ebox-42cef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdbgOkHYJyq2QC9GJQGWpmjFVf0xX2as8',
    appId: '1:308335910092:ios:0069953c66c4e4160cf669',
    messagingSenderId: '308335910092',
    projectId: 'ebox-42cef',
    databaseURL: 'https://ebox-42cef-default-rtdb.firebaseio.com',
    storageBucket: 'ebox-42cef.appspot.com',
    iosClientId: '308335910092-nsai141liqjs8ohumkm19tpfluco9lr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdbgOkHYJyq2QC9GJQGWpmjFVf0xX2as8',
    appId: '1:308335910092:ios:0069953c66c4e4160cf669',
    messagingSenderId: '308335910092',
    projectId: 'ebox-42cef',
    databaseURL: 'https://ebox-42cef-default-rtdb.firebaseio.com',
    storageBucket: 'ebox-42cef.appspot.com',
    iosClientId: '308335910092-nsai141liqjs8ohumkm19tpfluco9lr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebox',
  );
}
